spring.application.name=SpringSecurityExample

spring.security.user.name=pranab
spring.security.user.password=pranab45

spring.datasource.url=jdbc:postgresql://localhost:5432/SpringSecurityDB
spring.datasource.username=postgres
spring.datasource.password=User