spring.application.name=SpringOauth2Demo
server.port=8090

spring.security.oauth2.client.registration.github.client-id=Ov23liRd4RZ2uZZxnRam
spring.security.oauth2.client.registration.github.client-secret=013cb4cfaec133883c6cb7a6608095a20b852c3c